### ISSUE TITLE
example scripts

### ISSUE THREAD

**Issue by lisongx** [ucnv/aviglitch#1]
we can put some example scripts in a `example` folder, this way users can actully see how people use this library

**Comment by 12georgiadis** [comment]
Hi, when I use aviglitch and command $ datamosh, it always cut my avi file to 1,07GB. Whatever if it is 3GB fil source, 4GB or more... So I don't think it is related to the 32Bits 4,7GB avi limit. Config is Mac Os Sierra and files are between 4K and 6K, x264 100mbps (less than 1' and 2 or 3 cuts max). Regards, IJC

**Comment by ucnv** [comment]
I made a repository for some extended usage of this library (a long time ago...).
https://github.com/ucnv/aviglitch-utils
It might be a hint.
