### ISSUE TITLE
Make a command for frames manipulation

### ISSUE THREAD

**Issue by zigordlc** [ucnv/aviglitch#5]
Hi, I'm using your library (idk if that's what describes it) on termux, and it would be so much easier if I could just type a command to run this whole code:

```
require 'aviglitch'
  
a = AviGlitch.open 'file.avi'       # Rewrite this line for your file.
d = []
a.frames.each_with_index do |f, i|
  d.push(i) if f.is_deltaframe?     # Collecting non-keyframes indices.
end
q = a.frames[0, 5]                  # Keep first key frame.
100.times do
  x = a.frames[d[rand(d.size)], 1]  # Select a certain non-keyframe.
  q.concat(x * rand(50))            # Repeat the frame n times and concatenate with q.
end
o = AviGlitch.open q                # New AviGlitch instance using the frames.
o.output 'out.avi'
```

If adding a command is not possible, is there a way to at least make a file to execute this? I really wanna try it but don't know how.

**Comment by ucnv** [comment]
I have no plan to add commands to this library for now. Thank you.
And I can't answer how to set up the termux environment because I don't use it.
